version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"          
    environment:
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
